name: My_CI

on: [ push, pull_request ]

env:

jobs:
    main-job:
        runs-on: ubuntu-latest

        steps:
            - name: SETUP - Checkout git repo
              uses: actions/checkout@v2

            - name: SETUP - Set up build tools
              run: |
                  sudo apt-get update 
                  sudo apt-get install build-essentials cmake valgrind
            
            - name: SETUP - Ensure it is all set
              run: |
                  cmake --version
                  g++ --version

