name: My_CI

on: [ push ]

env:
    BUILD_DIR: build

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
        BUILD_DIR: build

    strategy:
      matrix:
        CMake_Config: [Debug, Release]
      fail-fast: false

    steps:
      - name: SETUP - Checkout git repo
        uses: actions/checkout@v2

      - name: SETUP - Set up build tools
        run: |
          sudo apt-get update 
          sudo apt-get install build-essential cmake=3.16.3-1ubuntu1 valgrind

      - name: SETUP - Ensure it is all set
        run: |
          cmake --version
          g++ --version

      - name: BUILD - CMake configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.CMake_Config }} -S . -B ${{ env.BUILD_DIR }} 

      - name: BUILD - CMake build
        run: |
          cmake --build ${{ env.BUILD_DIR }} 

      - name: TEST - CTest 
        run: |
          ctest -j10 -C ${{ matrix.CMake_Config }} -T test --output-on-failure -T test --output-on-failure
