name: My_CI

on: [ push, pull_request ]

env:
    BUILD_DIR: build

jobs:
    main-job:
        runs-on: ubuntu-latest

        steps:
            - name: SETUP - Checkout git repo
              uses: actions/checkout@v2

            - name: SETUP - Set up build tools
              run: |
                  sudo apt-get update 
                  sudo apt-get install build-essential cmake=3.16 valgrind

            - name: SETUP - Ensure it is all set
              run: |
                  cmake --version
                  g++ --version

            - name: BUILD - CMake configure
              run: |
                  cmake -S . -B ${{ env.BUILD_DIR }} 
                  cmake --build ${{ env.BUILD_DIR }} 
